[GLOBAL]
pants_version = "2.18.1"

backend_packages = [
  "pants.backend.python",
]

[python]
interpreter_constraints = ["==3.11.*"]
enable_resolves = true

[python.resolves]
python-default = "python.lock"